version: '3'

services:
    db:
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
            - MONGO_DB_NAME=${MONGO_DB_NAME}
        ports:
            - '${MONGO_PORT}:27017'
        volumes:
            - mongodb_data:/data/db

volumes:
    mongodb_data:
